[Info]
# Options for configuring Discord Spotify Integration (DSI)
# Fields in Required are just that, they're needed to connect to your Spotify account or Discord Application
# Everything below those is customisation
# Config v0.22.2.0535


[Required]

Spotify_Client_ID = 
# Your Spotify Client ID from, Spotify Developer Dashboard

Spotify_Client_Secret = 
# Your Spotify Client Secret, from Spotify Developer Dashboard

Spotify_Redirect_URI = 
# Your Spotify Redirect URI, from Spotify Developer Dashboard

Discord_Application_ID = 
# Your Discord Application ID, from Discord Application Developer Dashboard


[Function]

time_Between_Refresh = 15
# The amount of seconds between Discord RPC and Spotify new data refresh cycles
# Applies to both the data pull rate from Spotify and data push rate from Discord, if they're very desynced, you may see long periods with old data
# Very short refresh times may result in data not reaching the destination before the next cycle, leading to failed refreshes
# If you listen to songs from start to end, you likely won't notice longer refresh times - if you skip songs frequently, you will
# Please note that both services do have API rate limits, and too many requests may not only cause the program to fail, but you may get rate limited
# Default: 15
# Recommended range: 10-20
# Accepted values: any integer >5 (<5 is overwritten by safe minimum of 5)

enable_Pause_Behavior = True
# Whether to change the styling when song is paused
# Changes the timestamps to 0 when enabled and playback is paused
# This means instead of displaying how long the song is or how much is left, it counts up from the time the song was paused
# If disabled, always displays the normal appearance
# Default: True
# Accepted values: boolean (True/False)

pause_Behavior_Text = Paused on:
# The text displayed before song info, if pause behavior is enabled and playback is paused
# Default: Paused on:
# Default appearance: " Paused on: Song ≺ Artist ≻ Album "
# Accepted values: any string, nothing 
# Nothing is same as disabling pause behavior

print_Updates = True
# Whether to print info updates
# Contains the song status and Discord RPC status messages
# Note that startup messages aren't affected
# Default: True
# Accepted values: boolean (True/False)

print_Errors = True
# Whether to print errors
# Contains any potential error messages (note that Discord RPC errors are under print_Updates)
# Default: True
# Accepted values: boolean (True/False)

enable_URI_Mapping = True
# Whether to use URI mapping/storing
# This stores the track URIs in a JSON file as you listen
# These are later used by URImap.exe, if desired, to merge tracks with multiple URIs
# Set to true by default to allow track URI collection ASAP - collecting all the URIs may take days, if not weeks
# Default: True
# Accepted values: boolean (True/False)

market_Area = 
# This is the ISO 3166-1 alpha-2 country code your Spotify account belongs to
# This is only used with the URImap.exe function, where it'll combine track URIs, if one track has multiple
# Default: 
# Accepted values: any 2-letter country code
# Examples: US, CA, DE, JP, SN, CH

timestamp_Style = Uptime
# Changes the program timestamp format between system clock and uptime or disabled
# Default: Uptime
# Accepted values: Clock, Uptime, Off


[URL]
 
small_URL = https://elleffnotelf.com
# The URL you get when you click the smaller, round picture 
# Ensure proper format, Discord will reject non-https links and not update Activity
# Default: https://elleffnotelf.com
# Accepted values: any valid https link, nothing

spotify_URL = Track
# The URL you get when clicking the song information or clicking the large, square picture
# Always links to a Spotify link, type can be selected
# Note that Playlist link only works if you are playing a playlist, otherwise falls back to small_URL value
# Default: Track
# Accepted values: Track, Album, Artist, Playlist


[Song-Style]

# Default appearance: " Song ≺ Artist ≻ Album "
# Note that the limit for the song name field is 128 characters, the field will get cut off automatically
# The strings are UTF-8 encoded, so you can use all kinds of symbols - see https://en.wikipedia.org/wiki/List_of_Unicode_characters

song_Spacer_Left = ≺
# The string placed after the first element (song by default)
# Default: ≺
# Accepted values: any string, nothing

song_Spacer_Right = ≻
# The string placed after the second element (artist by default)
# Default: ≻
# Accepted values: any string, nothing


[Song-Format]

# Default appearance: " Song ≺ Artist ≻ Album "
# Note that the limit for the song name field is 128 characters, the field will get cut off automatically

pre_Text = 
# A string preceding the first element
# Default:
# Accepted values: any string, nothing
# Example: " preText Song ≺ Artist ≻ Album "

post_Text =
# A string placed after the final element 
# Default: 
# Accepted values: any string, nothing
# Example: " Song ≺ Artist ≻ Album postText "

enable_Song = True
# Whether the song name is listed
# Default: True
# Accepted values: boolean (True/False)
# If False, removes Left Song Spacer
# Example: " Artist ≻ Album "

enable_Artist = True
# Whether the artist name is listed
# Default: True
# Accepted values: boolean (True/False)
# If False, removes Left Song Spacer
# Example: " Song ≻ Album "

enable_Album = True
# Whether the album is listed
# Default: True
# Accepted values: boolean (True/False)
# If False, removes Right Song Spacer
# Example: " Song ≺ Artist "

enable_Album_Dropping = True
# Whether the program can drop the album name
# This happens if the state field is too long (Discord enforces a 128-character UTF-16 limit)
# Default: False
# Accepted values: boolean (True/False)

album_Fallback_Text = 
# Text to use if album cannot be added to the song state field
# Default:
# Accepted values: any string, nothing
# Recommended: keep short, otherwise it'll just end up getting cut itself


[Pictures]

pictures_To_Cycle = Spotify
# A list of the large (square) pictures to cycle between
# Enter the pictures themselves into pictureList.txt
# An empty value is accepted, will not load a picture
# Setting it to " File " reads the picture list from the included pictureList.txt file
# Setting it to " Spotify " will take the album covers and use those (disables cycling)
# Default: Spotify
# Accepted values: Spotify, File, nothing
# Recommended: use extrenal links, Discord caching is inconsistent at best

picture_Cycle_Time = 30
# The amount of minutes between picture changes
# Note that the picture only updates when a new song is found
# Default: 30
# Accepted values: any positive integer

picture_Cycle_Behavior = Random
# How the pictures rotate
# Default: Random
# Accepted values: Random, Sequence, Once, None
# Random cycles a picture every cycle time
# Sequence goes through a picture in list order every cycle time
# Once chooses a random picture at start
# None is the same as only having one picture - picks the first picture

small_Picture_Name = 
# The name of the smaller (round) picture on your Activity
# Note: empty value is accepted, will not load a picture
# If you set a picture here, but not in the (large) picture field, this will be used in the large field instead
# Default: 
# Accepted format: "picture" or "https://picturelink.com/picture.png"
# Accepted values: any valid picture name matching one in Art Assets or a valid external picture URL
# Recommended: use an extrenal link, Discord caching is inconsistent at best

text_On_Small_Hover = Spotify
# The text that appears when you hover over the smaller (round) picture
# Default: Spotify
# Accepted values: any string, nothing


[SHAA-Song-Function]

# Most of the fields corresponding to the numbers below don't exist as information you can request from Spotify
# If so, they'll require Spotify Analyser to provide them (https://github.com/EllEff-Git/Spotify-Analyzer)
# If using DSI as an addon to Spotify Analyser, ensure proper installation of both (https://elleffnotelf.com/guides/Spotify-Analyser)

song_Info_First_Field = Track
# Type of information listed in the first field of the details
# Default: Track
# Accepted values: Track, Total, any string
# Track finds the number of plays for current track
# Total finds the total number of plays for all tracks
# Use a custom string if not using with SHA, displayed as-is
# Example: " 1,234 plays ", " 123,456 total plays", " custom field text "
# Use in tandem with song_Info_Format_First_Field to stylise this field fully

song_Info_Second_Field = Track
# Type of information listed in the second field of the details
# Default: Track
# Accepted values: Track, Total, any string
# Track finds the minutes played for current track
# Total finds the total minutes played for all tracks
# Use a custom string if not using with SHA, displayed as-is
# Example: " 5,678 minutes ", " 56,789 total minutes ", " custom field text "
# Use in tandem with song_Info_Format_Second_Field to stylise this field fully

song_Info_Fallback = Total
# What data type to fall back on, in case the current song cannot be found
# Affects playcount and playtime
# Default: Total
# Accepted values: Total, any string
# Total displays the total playcount and playtime for all tracks
# Any other string is displayed as-is
# Use in tandem with song_Info_Fallback_Format to stylise this fallback field

song_Info_Detail_Field = Hours
# What type of data to show in the detail field
# Overridden by the string above
# Default: Hours
# Accepted values: Hours, Volume, Repeat, Shuffle, any string
# Hours displays the total hours, in number format (requires SHA)
# Volume displays the current volume, in percentage points
# Repeat displays either "on Repeat" or "not on Repeat"
# Shuffle displays either "on Shuffle" or "not on Shuffle"
# Any custom string is displayed as-is


[SHAA-State-Format]

# If using with SHA, the format for "state" is: playcount (type by song_Info_First_Field) + format_plays + info_spacer + playtime (type by song_Info_Second_Field) + format_mins
# If using without SHA, the format for "state" is: song_Info_First_Field + song_Info_Spacer + song_Info_Second_Field
# Keep this in mind when customising your fields

song_Info_Format_First_Field = plays
# The styling for the first field (playcount)
# Default: plays
# Accepted values: any string

song_Info_Spacer = ※
# The string placed between the first and second fields
# Default: ※
# Default appearance: " 1,234 plays ※ 5,678 minutes "
# Accepted values: any string

song_Info_Format_Second_Field = minutes
# The styling for the second field (playtime)
# Default: minutes
# Accepted values: any string

song_Info_Fallback_Format = total
# The styling for fields 1 and 2 to fall back on, in case the current song cannot be found
# Default: total
# Default appearance: " 1,234 total plays ※ 5,678 total minutes "
# Accepted values: any string, nothing


[SHAA-Details-Format]

# If using with SHA, the format for "details" is: 
# If using without SHA, the format for "details" is: 
# Keep this in mind when customising your fields

song_Info_Format_Details = Total Hours
# The styling for details field
# Default: Total Hours
# Default appearance: " Total Hours: 12,345 "
# Accepted values: any string

song_Info_Format_Details_Spacer = :
# The styling between the detail field and the detail field format
# Automatically adds a space after
# Default: :
# Default appearance: " Total Hours: 12,345 "
# Accepted values: any string

song_Info_Double_Space = False
# Whether to add space to both sides of the detail field spacer
# Intended to use if spacer/format is customised
# Default: False
# Default appearance: " Total Hours: 12,345 "
# Accepted values: boolean (True/False)
# Examples: " Total Hours ※ 12,345 ", " Total Hours = 12,345 "

dsi_Shoutout = False
# Whether to add a shoutout to DSI :)
# Adds a tag to the end of the details field (total hours)
# Default: False
# Accepted values: boolean (True/False)
# Appearance: " Total Hours: 12,345 // Data by DSI "