[Info]
# Options for configuring Discord Spotify Integration (DSI)
# Fields in Required are just that, they're needed to connect to your Spotify account or Discord Application
# Everything below those is customisation


[Required]

Spotify_Client_ID = 
# Your Spotify Client ID from, Spotify Developer Dashboard

Spotify_Client_Secret = 
# Your Spotify Client Secret, from Spotify Developer Dashboard

Spotify_Redirect_URI = 
# Your Spotify Redirect URI, from Spotify Developer Dashboard

Discord_Application_ID = 
# Your Discord Application ID, from Discord Application Developer Dashboard


[Function]

time_Between_Refresh = 15
# The amount of seconds between Discord RPC refresh cycles
# Applies to both the data pull rate from Spotify and data push rate from Discord, if they're very desynced, you may see long periods with old data
# Very short refresh times may result in data not reaching the destination before the next cycle, leading to failed refreshes
# If you listen to songs from start to end, you likely won't notice longer refresh times - if you skip songs frequently, you will
# Please note that both services do have API rate limits, and pulling data too frequently may not only cause the program to fail, but you may get rate limited or even blocked
# Default: 15
# Recommended range: 10-20
# Accepted values: any integer > 5 (lower value gets overwritten to minimum of 5)

enable_Pause_Behavior = True
# Whether to change the styling when song is paused
# Changes the timestamps to 0 when enabled and playback is paused
# This means instead of displaying how long the song is or how much is left, it counts up from the time the song was paused
# If disabled, always displays the normal appearance
# Default: True
# Accepted values: boolean (True/False)

pause_Behavior_Text = Paused on:
# The text displayed before song info, if pause behavior is enabled and playback is paused
# Default: Paused on:
# Default appearance: " Paused on: Song ≺ Artist ≻ Album "
# Accepted values: any string


[URL]
 
small_URL = https://elleffnotelf.com
# The URL you get when you click the smaller, round picture 
# Ensure proper format, Discord will reject non-https links and not update Activity
# Default: https://elleffnotelf.com
# Accepted values: any valid https link

spotify_URL = Track
# The URL you get when clicking the song information or clicking the large, square picture
# Always links to a Spotify link, type can be selected
# Note that Playlist link only works if you are playing a playlist, otherwise falls back to small_URL value
# Default: Track
# Accepted values: Track, Album, Artist, Playlist


[Song-Style]

# Default appearance: " Song ≺ Artist ≻ Album "
# Note that the limit for the song name field is 128 characters, the field will get cut off automatically
# The strings are UTF-8 encoded, so you can use all kinds of symbols - see https://en.wikipedia.org/wiki/List_of_Unicode_characters

song_Spacer_Left = ≺
# The string placed after the first element (song by default)
# Default: ≺
# Accepted values: any string

song_Spacer_Right = ≻
# The string placed after the second element (artist by default)
# Default: ≻
# Accepted values: any string


[Song-Format]

# Default appearance: " Song ≺ Artist ≻ Album "
# Note that the limit for the song name field is 128 characters, the field will get cut off automatically

pre_Text = 
# A string preceding the first element
# Default:
# Accepted values: any string
# Example: " preText Song ≺ Artist ≻ Album "

post_Text = 
# A string placed after the final element 
# Default: 
# Accepted values: any string
# Example: " Song ≺ Artist ≻ Album postText "

enable_Song = True
# Whether the song name is listed
# Default: True
# Accepted values: boolean (True/False)
# If False, removes Left Song Spacer
# Example: " Artist ≻ Album "

enable_Artist = True
# Whether the artist name is listed
# Default: True
# Accepted values: boolean (True/False)
# If False, removes Left Song Spacer
# Example: " Song ≻ Album "

enable_Album = True
# Whether the album is listed
# Default: True
# Accepted values: boolean (True/False)
# If False, removes Right Song Spacer
# Example: " Song ≺ Artist "


[Pictures]

pictures_To_Cycle = 
# A list of the large (square) pictures to cycle between
# Note: empty value is accepted, will not load a picture
# Default: 
# Accepted format: "picture1", "picture2", "https://picturelink.com/picture3.png", "https://i.imgur.com/picture4.png"
# Accepted values: single or list of valid picture names matching one in Art Assets or a valid external picture URLs
# Recommended: use an extrenal link, Discord caching is inconsistent at best

picture_Cycle_Time = 60
# The amount of minutes between picture changes
# Default: 60
# Accepted values: any integer

picture_Cycle_Behavior = Random
# How the pictures rotate
# Default: Random
# Accepted values: Random, Sequence, Once, None
# Random cycles a picture every cycle time
# Sequence goes through a picture in list order every cycle time
# Once chooses a random picture at start
# None is the same as only having one picture - picks the first picture

small_Picture_Name = 
# The name of the smaller (round) picture on your Activity
# Note: empty value is accepted, will not load a picture
# Default: 
# Accepted format: "picture" or "https://picturelink.com/picture.png"
# Accepted values: any valid picture name matching one in Art Assets or a valid external picture URL
# Recommended: use an extrenal link, Discord caching is inconsistent at best

text_On_Small_Hover = Spotify
# The text that appears when you hover over the smaller (round) picture
# Default: Spotify
# Accepted values: any string


[SHAA-Song-Info]

# The fields corresponding to the numbers below don't exist as information you can request from Spotify
# They all require Spotify Analyser to provide them (https://github.com/EllEff-Git/Spotify-Analyzer)
# If using DSI as an addon to Spotify Analyser, ensure proper installation of both (https://elleffnotelf.com/guides/Spotify-Analyser)


song_Info_Empty_Field = N/A
# The appearance of data when it's missing
# Affects playcount (plays per track), playtime (min per track) and total time (total hours)
# Default: N/A
# Default appearance: " Total Hours: N/A "
# Accepted values: any string

song_Info_Spacer = ※
# The string placed between the times played and minutes
# Default: ※
# Default appearance: " 1,234 plays ※ 5,678 minutes "
# Accepted values: any string

song_Info_Format_Plays = plays
# The styling for track playcount
# Default: plays
# Accepted values: any string

song_Info_Format_Mins = minutes
# The styling for track playtime
# Default: minutes
# Accepted values: any string

song_Info_Format_Hours = Total Hours
# The styling for total hours
# Default: Total Hours
# Default appearance: " Total Hours: 12,345 "
# Accepted values: any string

song_Info_Format_Hour_Spacer = :
# The styling between the hour format and the total hours
# Automatically adds a space after
# Default: :
# Default appearance: " Total Hours: 12,345 "
# Accepted values: any string

song_Info_Double_Space = False
# Whether to add space to both sides of the spacer
# Intended to use if spacer is changed to a custom one
# Default: False
# Default appearance: " Total Hours: 12,345 "
# Accepted values: boolean (True/False)
# Examples: " Total Hours ※ 12,345 ", " Total Hours = 12,345 "