[Info]
# Options for configuring Discord Spotify Integration (DSI)
# Fields in Required are just that, they're needed to connect to your Spotify account or Discord Application
# Function has options that modify the program function
# Config v0.4.6.1652


[Required]

Spotify_Client_ID = 
# Your Spotify Client ID, from Spotify Developer Dashboard

Spotify_Client_Secret = 
# Your Spotify Client Secret, from Spotify Developer Dashboard

Spotify_Redirect_URI = 
# Your Spotify Redirect URI, from Spotify Developer Dashboard

Discord_Application_ID = 
# Your Discord Application ID, from Discord Application Developer Dashboard


[Function]

Skip_Config_Window = False
# Whether to skip the configurator window
# Option is ignored if a valid config file isn't found
# Default: False
# Accepted values: boolean (True/False)