import os, sys, json, time, datetime
import spotipy, configparser, requests
from spotipy import SpotifyOAuth
from spotipy import SpotifyException

URIver = "v0.3.04.0855"
# the program version (y.m.dd.hhmm)


# Directory Grabber
if getattr(sys, 'frozen', False):
    # since the program bundled with pyInstaller, it's "frozen"
    directory = os.path.dirname(sys.executable)
    # gets the base directory of the program, where the python .exe resides
    """Directory should be DSI/Data/URImap.exe"""
else:
    # if somehow not in a bundled (frozen) state
    directory = os.path.dirname(__file__)
    # gets the base directory of the program, where the python .exe resides


# Directory Definitions
uriDir = os.path.join(directory, "Data", "URImap.json")
"""the directory where URImap.json should/will live (inside DSI/Data/URImap.json)"""
noURIdir = os.path.join(directory, "Data", "URIlist.json")
"""The directory where URIlist.json should/will live (inside DSI/Data/URIlist.json)"""
spCache = os.path.join(directory, "Data", "spotifycache.json")
"""the directory where the spotify cache (token) sits in"""


# Config
Config = configparser.ConfigParser(comment_prefixes = ["/", "#"], allow_no_value = True)
# sets up the config reader
ConfigPath = os.path.join(directory, "config.ini")
# calls the pathFinder to give the location of "config.ini"
Config.read(ConfigPath, "utf8")
# reads from the config, saves values below


# Required
sp_client_ID = Config.get("Required", "Spotify_Client_ID")
"""spotify client ID, string"""
sp_client_secret = Config.get("Required", "Spotify_Client_Secret")
"""spotify client secret, string"""
sp_redirect = Config.get("Required", "Spotify_Redirect_URI")
"""spotify redirect URL, string"""
MarketArea = Config.get("Function", "market_Area")
"""The 2-letter country identifier passed to spotify"""


# Session
sessionID = requests.Session()
# tells the auth to keep one stable connection, rather than re-connecting every request

# Auth
authorisation = SpotifyOAuth(
    scope = "user-library-read",
    client_id = sp_client_ID, 
    client_secret = sp_client_secret, 
    redirect_uri = sp_redirect,
    cache_path = spCache
    )
# the arguments for auth_manager, containing the variables from config + scope of data request

main = spotipy.Spotify(auth_manager = authorisation, requests_session = sessionID)
# handles the authentication and user identification on start


# Timestamp
def Time():
    """Function that returns the current time, formatted"""
    return datetime.datetime.now().strftime("%H:%M:%S")
    # shortens the time call into a function with 00:00:00 format


# URI Prerequisites

if os.path.exists(uriDir):
    # checks if the uri mapping file (URImap.json) exists
    with open(uriDir, "r", encoding="utf-8") as urimap:
        # loads the uri mapping file
        uriMap = json.load(urimap)
        # stores the loaded file as uriMap
else:
    # if the file doesn't exist, creates a new (empty) mapping
    uriMap = {}

with open(noURIdir, "r") as uris:
    # opens the uriList.json file
    uriList = json.load(uris)
    # stores the list in a variable



### URI JSON Mapper ###



def mapper(start, end):
    """Function that takes URIs from the list generated by DSI and turns into a keymap"""

    for num, uri in enumerate(uriList[start:end], start=start):
        # gets the URI (track ID) for every unique entry in the CSV

        if num == start:
            # prints on the first URI of the batch
            print(f"{Time()} [UMAP]: URI mapping started")

        if num % 25 == 0:
            # prints every 25 URIs
            print(f"{Time()} [UMAP]: Mapping process: {num} out of {end}")

        if num == (end-1):
            # prints on the last URI of the batch
            print(f"{Time()} [UMAP]: Mapping complete")

        if uri not in uriMap:
            # for every track URI not found in the pre-existing URI mapped JSON file

            try:
                # tries to find it via Spotify
                trackInfo = main.track(uri, MarketArea)
                # requests the track data from Spotify with the ID and market ID
                altURI = f"spotify:track:{trackInfo["id"]}"
                # it stores the "alternate URI" (the ID spotify returns for your market) as a string
                uriMap[uri] = altURI
                # and then stores that inside the URI map file

            except SpotifyException as error:
                # if it fails, saves the error

                if error.http_status == 429:
                    # if the error is exactly 429 (rate limit)

                    print(f"{Time()} [WARN]: Spotify rate limit exceeded, waiting for cooldown")
                    # prints the rate limit info
                    retryTimer = int(error.headers["Retry-After"])
                    # takes the given "retry after" timer and saves it
                    returnTime = datetime.datetime.fromtimestamp(int(retryTimer + time.time() + 3)).strftime("%H:%M:%S")
                    # gets the return time (time the cooldown expires)
                    print(f"{Time()} [WARN]: Rate limit cooldown is {retryTimer} ({returnTime})")
                    # prints the cooldown info
                    print(f"{Time()} [EXIT]: Exiting app in 10 minutes automatically (feel free to close)")
                    time.sleep(600)
                    # sleeps for 600 seconds (10 minutes) to ensure user sees prompt
                    raise SystemExit
                else:
                    None
            
            except PermissionError as error:

                if getattr(error, "winerror", None) == 10013:
                    # if the error is specifically a windows 10013 error (connection blocked for one reason or another)
                    print(f"{Time()} [WARN]: Windows has blocked the connection, please check firewall/antivirus settings and retry (WinError 10013)")
                    print(f"{Time()} [INFO]: Sometimes this is due to odd Windows behavior, and a restart may fix this")
                    print(f"{Time()} [EXIT]: Exiting app in 10 minutes automatically (feel free to close)")
                    time.sleep(600)
                    # sleeps for 600 seconds (10 minutes) to ensure user sees prompt
                    raise SystemExit
                else:
                    None
            
            else:
                print(f"{Time()} [ERROR]: Failure fetching {uri}:\n{Time()} [ERROR]: {error}")
                # prints the error message
                uriMap[uri] = uri
                # uses the original URI for the current URI

            time.sleep(0.25)
            # safety implementation, to avoid Windows/Spotify rate limits

    with open(uriDir, "w", encoding="utf-8") as newUri:
        # opens the JSON file in write mode
        json.dump(uriMap, newUri, ensure_ascii=False, indent=2)
        # pushes the data from newUri to the JSON file

    print(f"{Time()} [INFO]: Done mapping batch")
    # user update
    time.sleep(2)
    # short wait
    print(f"{Time()} [INFO]: Checking URI list")
    # user update

    while True:
        undoneCheck = batchCalc(15)
        # ensures there's no functions running before re-checking
        if not undoneCheck:
            break



### Mapper Variable Calculation ###



def batchCalc(pause):
    """Function that calculates the batch size of URIs and starts mapper"""

    uriLength = (len(uriList))
    # stores the total length of the URI list

    currentLength = len(uriMap)
    # stores the total length of the URI mapping

    length = (uriLength - currentLength)
    # calculates the length the batch worker has to do

    maxLength = 101
    # sets a max worker size of 101 (number I'm *fairly* certain Spotify won't limit)

    print(f"{Time()} [INFO]: Waiting {pause} seconds to start...")
    # quick user update on wait

    time.sleep(pause)
    # sleeps for the parameter-set length (0 at start, a bit after first batch, to prevent insane spam to API)

    print(f"{Time()} [INFO]: {uriLength} URIs stored by DSI, {currentLength} already mapped")
    # user inform on task length

    if not MarketArea:
        # if the config option is empty
        print(f"{Time()} [ERROR]: No market area. Please input it in the config.ini file and try again. Exiting mapper")
        # user inform, wait -> exit
        time.sleep(10)
        raise SystemExit

    if (uriLength - currentLength) < 1:
        # if the URImap is longer than or equal to the uriList
        print(f"{Time()} [EXIT]: All URIs mapped. Exiting app in one minute (feel free to close)")
        # user inform, wait -> exit
        time.sleep(60)
        raise SystemExit

    if length > maxLength:
        # if the URI list queue exceeds maximum allowed size
        print(f"{Time()} [INFO]: Current maximum batch size is {maxLength}, but there are {length} unprocessed URIs. Processing max batch size")
        # informs user
        taskLength = maxLength
        # sets the task length to the maximum allowed batch size

    else:
        # if the URI list queue is shorter than max allowed batch size
        print(f"{Time()} [INFO]: Processing {length} URIs")
        # informs user
        taskLength = length
        # sets the queue length as the max


    taskEnd = currentLength + taskLength
    # calculates the end of the task by adding current max and the chosen length


    print(f"{Time()} [START]: Starting URImapper {URIver}")
    # starting program user inform
    time.sleep(2)

    mapper(currentLength, taskEnd)
    # starts new task with the start and end points



### PROGRAM START ###


batchCalc(0)
# calls batch size calculator


### END ###


print(f"{Time()} [EXIT]: Task complete - exiting app in one minute (feel free to close now)")
# user update
time.sleep(60)
# wait so it doesn't look like crash